name: Relatório de Bug
description: Envie um relatório de bug
title: "[Bug]: "
labels: ["bug", "triagem necessária"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por dedicar um tempo para preencher este relatório de bug!
  - type: checkboxes
    attributes:
      label: Já existe uma issue para isso?
      description: Por favor, pesquise para ver se já existe uma issue para o bug que você encontrou.
      options:
      - label: Eu pesquisei nas issues existentes
        required: true
  - type: checkboxes
    attributes:
      label: Existe uma pergunta no StackOverflow sobre esse problema?
      description: Por favor, pesquise no [StackOverflow](https://stackoverflow.com/questions/tagged/android-jetpack) se já existe uma resposta para o bug que você encontrou.
      options:
      - label: Eu pesquisei no StackOverflow
        required: true
  - type: textarea
    id: what-happened
    attributes:
      label: O que aconteceu?
      description: Também nos diga o que você esperava que acontecesse.
      placeholder: Conte-nos o que você viu!
      value: "Um bug aconteceu!"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Saída relevante do logcat
      description: Por favor, copie e cole qualquer saída relevante do logcat. Isso será formatado automaticamente como código, então não é necessário usar crases.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Código de Conduta
      description: Ao enviar esta issue, você concorda em seguir nosso [Código de Conduta](CODE_OF_CONDUCT.md)
      options:
        - label: Eu concordo em seguir o Código de Conduta deste projeto
          required: true