name: Problema na Documentação
description: Registre um problema ou faça uma sugestão para a documentação do projeto
title: "[Documentação]: "
labels: ["documentação"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por dedicar um tempo para melhorar nossa documentação!
  - type: checkboxes
    attributes:
      label: Já existe uma issue para isso?
      description: Por favor, pesquise para ver se já existe uma issue relacionada ao problema de documentação que você encontrou.
      options:
      - label: Eu pesquisei nas issues existentes
        required: true
  - type: input
    id: page-url
    attributes:
      label: URL da página (digite "NOVA" para sugerir uma nova página)
    validations:
      required: true
  - type: textarea
    id: what-needs-improving
    attributes:
      label: Qual é o problema ou sugestão de documentação?
      placeholder: Conte-nos o que deve ser melhorado!
      value: "A documentação precisa ser melhorada!"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Código de Conduta
      description: Ao enviar esta issue, você concorda em seguir nosso [Código de Conduta](CODE_OF_CONDUCT.md)
      options:
        - label: Eu concordo em seguir o Código de Conduta deste projeto
          required: true